### DISCUSSION TITLE
Cannot set up route/entry for Wordpress in docker-compose

### DISCUSSION THREAD

**Discussion by Currrupted** [umputun/reproxy#127] [Q&A] [answered]
Hey there! I stumbled across your project and I am really digging it so far! I am trying to set up Reproxy as a reverse proxy in my Docker Compose set up. I want to build a setup for my husband's web presence, using Docker.

Unfortunately, I am currently unable to implement Reproxy correctly. So far I have both Reproxy and  Wordpress containers (one each). This is what I'm trying to achieve. When connecting to `localhost`, Reproxy should redirect/connect to the Wordpress container. I want to add a Mailcow installation later, so the Wordpress container should be the default when connecting to the domain. So when I enter http://localhost I should see my website and/or Wordpress Dashboard.

Unfortunately this doesn't work for me yet and I cannot tell why...

This is my compose file for Reproxy:
```
services:
  reproxy:
    image: umputun/reproxy:master
    container_name: reproxy
    hostname: reproxy
    ports:
      - "80:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./web:/web
    environment:
      - TZ=Europe/Amsterdam
      - LISTEN=0.0.0.0:8080
      - DOCKER_ENABLED=true
      - DOCKER_AUTO=false
      - DEBUG=true
      - SSL_TYPE=none
```

This is the compose settings in the file for Wordpress:
```
wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    hostname: wordpress
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    labels:
      - reproxy.enabled= true
      - reproxy.server= localhost
      - reproxy.port=80
```

When I try to access `http://localhost`, I only see `Server error`... I feel like I am doing something wrong, but I tried everything and don't know how to fix this. Thank you!
