### ISSUE TITLE
[Feature request]get host in route rule

### ISSUE THREAD

**Issue by leopku** [umputun/reproxy#189]
It seems reproxy doesn't support get host in route rule.

For example:
```yaml
- { route: "^/api/svc1/(.*)", dest: "http://s3.my.domain/public/${host}/blah1/$1" }
```

**Comment by umputun** [comment]
Not sure I understand the request. I guess this is about the static file provider, and if this is the case, you can already define the host, not as part of the rule itself you provided, but rather as a higher-level "key".

```yml
default:
  - {route: "^/api/svc1/(.*)", dest: "http://127.0.0.1:8080/blah1/$1"}
  - {route: "/api/svc3/xyz", dest: "http://127.0.0.3:8080/blah3/xyz", "ping": "http://127.0.0.3:8080/ping"}
  - {route: "/web/", dest: "/var/web", "assets": yes, "keep-host": yes,  "remote": "192.168.1.0/24, 124.0.0.1"}
  - {route: "/web2/", dest: "/var/web2", "spa": yes, "keep-host": no}
srv.example.com:
  - {route: "^/api/svc2/(.*)", dest: "http://127.0.0.2:8080/blah2/$1/abc"}
```

This config defines two sets of rules - one for srv.example.com and another (default) as a catch-all-others
