### ISSUE TITLE
[question] is there a way to serve static files from multiple locatons ?

### ISSUE THREAD

**Issue by vitalik** [umputun/reproxy#27]
Is it possible to make some mapping like this:

```
- site1.com/api/    ---> docker.container1
- site1.com/static/ ---> static path /var/www/staticfolder1
- site2.com/api/    ---> docker.container2
- site2.com/static/ ---> /var/www/anotherfolder
```

**Comment by umputun** [comment]
this was mentioned as a part of https://github.com/umputun/reproxy/issues/20

> Attempt to serve fully static content with separate reproxy containers (see #12) worked, but looks a little bit odd. I'm not sure if I like it or maybe prefer some other approach

Currently reproxy has a single asset's location per instance. However, nothing prevents the user from running multiple reproxy instances, each one for a separate static location.

For example, in one of my usages I have smth like this for additional static locations:

```
  umputun.com:
    image: umputun/reproxy:master
    container_name: umputun.com
    hostname: umputun.com
    restart: always
    logging: *default_logging
    labels:
      reproxy.server: umputun.com,www.umputun.com
    environment:
      - ASSETS_LOCATION=/www
      - LISTEN=0.0.0.0:8080
    volumes:
      - ./www/umputun.com:/www
    ports:
      - 8080

  reproxy.io:
    image: umputun/reproxy:master
    container_name: reproxy.io
    hostname: reproxy.io
    restart: always
    logging: *default_logging
    labels:
      reproxy.server: reproxy.io
    environment:
      - ASSETS_LOCATION=/www
      - LISTEN=0.0.0.0:8080
    volumes:
      - ./www/reproxy.io:/www
    ports:
      - 8080
```
I'm open to suggestions how to make it simpler, but this should work with any provider and not overcomplicate the setup

**Comment by umputun** [comment]
how about this: we can extend the destination with a prefix, for example, `static:`, i.e. in any place we put destination, we could write something like `static:/www/mysite`. This rule will be used instead of the generic one. Probably we could get rid of the current assets params as this destination extension should cover it as well.

**Comment by vitalik** [comment]
maybe something like this:
```YAML
  whoami:
    image: 'containous/whoami'
    volumes:
      - ./static:/static
    labels:
      reproxy.server: '*'
      reproxy.route: '^/whoami/(.*)'
      reproxy.dest: '/$$1'
      reproxy.assets: '/static:/path/on/host/cwd/static'    # <------- !!! 
```
add label `reproxy.assets` which can have mapping of the extra route to path on the host

**Comment by umputun** [comment]
I thought about it today and can't see how the idea of multiple sites can work in practice. For static rules and file rules it makes some sense, but for docker or any other non-FS-based provider - I just don't see what it suppose to mean. Let's say a container defines `reproxy.static` rule like static/ -> /var/www/anotherfolder. What this even supposed to mean? where /var/www/anotherfolder is coming from? It is unlikely to be a part of the container itself as I don't see how reproxy can share files from the external container, but if this is host-level or reproxy-level directory it doesn't make much sense either.

In your sample above It doesn't make sense to me either. I kind of get the idea, you want on the container level direct reproxy to serve files (on what path? root?) from /path/on/host/cwd/static. The issue here is the container providing meta info for reproxy and `/path/on/host/cwd/static` is very confusing, as the host path is not the same as reproxy (container) path. To make all of this work reproxy container will have to map (with volume) some host locations.

**Comment by umputun** [comment]
In addition, can someone provide me a practical use case for such multi-site functionality. So far in all 3 systems, I have migrated to reproxy I have not even seen a case with reproxy providing normal reverse proxy location and assets (single location) at the same time.

in the case of a single application compose with a single set of static pages and multiple API services (containers) I see how this can be used theoretically, but practically I found this really awkward. How one even suppose to update static pages? Is it a volume of some other container mapped to reproxy container or just a directory on the host FS? If so, how exactly this directory will coexist with everything else living in containers?

**Comment by umputun** [comment]
@vitalik - check the current master out, it has the support of multiple static file servers for all providers

**Comment by vitalik** [comment]
@umputun 

well I managed to make static work, but now it does not proxy http to the container:

this is my setup:

![CleanShot 2021-04-16 at 12 13 31](https://user-images.githubusercontent.com/95222/115002249-30314c00-9ead-11eb-81ee-a0b807ee6224.png)


```YAML
services:
  reproxy:
    image: umputun/reproxy:master
    container_name: reproxy
    hostname: reproxy
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./assets:/assets
    environment:
      - LISTEN=0.0.0.0:8080
      - DOCKER_ENABLED=true
      # - DOCKER_AUTO=true
      # - ASSETS_LOCATION=/assets
      - DEBUG=true

  whoami1:
    image: 'containous/whoami'
    hostname: whoami1
    volumes:
      - ./assets/static1:/assets/static1
    labels:
      reproxy.server: 'localhost'
      reproxy.assets: '/static:/assets/static1'
      

  whoami2:
    image: 'containous/whoami'
    hostname: whoami2
    volumes:
      - ./assets/static2:/assets/static2
    labels:
      reproxy.server: '127.0.0.1'
      reproxy.assets: '/static:/assets/static2'

```

If I go to `http://localhost:9999/static` - I can see my static index.html
but `http://localhost:9999` - gives 404

and if I remove `reproxy.assets: '/static:/assets/static2'` label - the `http://localhost:9999` works

**Comment by umputun** [comment]
First of all, volumes mapping in whoami1 and whoami2 container don't affect anything and not needed. All those containers do is providing mapping to reproxy container. So, `volumes` in reproxy service the only thing that matters for assets.

The second part - I don't understand why you even expect http://localhost:9999 to work. You don't have any rule for this (ASSETS_LOCATION commented out), the only assets mapping you set is for /static which is kind of conflicting (both for /static root url)

**Comment by vitalik** [comment]
@umputun 
ok... back to original ticket story

I have 2 sites site1.com and site2.com pointing to the the same ip address (the host)

to make it less confusing with 127.0.0.1 and localhost I created 2 hosts in my  /etc/hosts file:

```
127.0.0.1   site1.com
127.0.0.1   site2.com
```

This is my docker-compose.yml now

```YAML
services:
  reproxy:
    image: umputun/reproxy:master
    container_name: reproxy
    hostname: reproxy
    ports:
      - "80:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./assets:/assets
    environment:
      - LISTEN=0.0.0.0:8080
      - DOCKER_ENABLED=true
      - DEBUG=true

  whoami1:
    image: 'containous/whoami'
    labels:
      reproxy.server: 'site1.com'
      reproxy.assets: '/static:/assets/static1'
      

  whoami2:
    image: 'containous/whoami'
    labels:
      reproxy.server: 'site2.com'
      reproxy.assets: '/static:/assets/static2'

```

now tests:


![CleanShot 2021-04-16 at 21 55 32](https://user-images.githubusercontent.com/95222/115071136-84b0e780-9efe-11eb-9ba5-f16885f8e043.png)
---

![CleanShot 2021-04-16 at 21 56 05](https://user-images.githubusercontent.com/95222/115071167-92666d00-9efe-11eb-88f9-a25339637d63.png)
---
![CleanShot 2021-04-16 at 21 56 28](https://user-images.githubusercontent.com/95222/115071201-9e522f00-9efe-11eb-8075-33c2693dae5d.png)
---
![CleanShot 2021-04-16 at 21 56 47](https://user-images.githubusercontent.com/95222/115071234-aad68780-9efe-11eb-8f1e-861188a873a9.png)
---
so `/static` is working fine for site1 and site2 (throwing different index html files)

but `/` - i would expect whoami responses

-----

Now if I remove `reproxy.assets` label:

```YAML
  whoami1:
    image: 'containous/whoami'
    labels:
      reproxy.server: 'site1.com'
      # reproxy.assets: '/static:/assets/static1'    # !!!!!!!!! 
```
whoami starts to output: 

![CleanShot 2021-04-16 at 22 06 21](https://user-images.githubusercontent.com/95222/115072264-05241800-9f00-11eb-9482-34734fcad383.png)

code attached

[reproxytest.zip](https://github.com/umputun/reproxy/files/6327405/reproxytest.zip)

**Comment by umputun** [comment]
thx for the example, it helped to understand the issue you described.

The bottom line - as soon as I see `reproxy.assets` label I treat the container for assets mapping only and not as the regular proxy destination. It is possible to do both (like you expect), however, it's raising a new problem - how to treat containers with  `reproxy.assets`  what not supposed to be a proxy destination? One of the ideas - if the container has `reproxy.enabled` explicitly and has  `reproxy.assets` this will be the indication of "we want both proxy and static", overwise it will be just static.

Kind of confusing I think. Any better ideas?

**Comment by vitalik** [comment]
yeah, it's not clear how to handle case when you need to host ONLY static (which is not the often case I can imagine)

there should be multiple rules per container ?

```YAML
  labels:
      reproxy.server: 'site.com'
      # rule 1
      reproxy.route.1: '^/api/(.*)'
      reproxy.dest.1: '/$$1'
      # rule 2
      reproxy.route.2: '^/static/(.*)'
      reproxy.dest.2: 'assets:/path/on/the/host/$$1'
```
naming is not perfect... but just a direction where this can go

multiple rules can be also helpful when I want to proxy multiple paths like `/api/` , `/dashboard/` with one container
