### ISSUE TITLE
Route priority

### ISSUE THREAD

**Issue by vitalik** [umputun/reproxy#55]
```YAML
services:
  reproxy:
    image: umputun/reproxy:master
    container_name: reproxy
    hostname: reproxy
    ports:
      - "80:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./assets:/assets
    environment:
      - LISTEN=0.0.0.0:8080
      - DOCKER_ENABLED=true
      - DEBUG=true

  whoami1:
    image: 'containous/whoami'
    labels:
      reproxy.enabled: y
      reproxy.server: 'localhost'
      reproxy.route: '^/whoami/(.*)'      # <------------!!! 
      reproxy.dest: '/$$1'
      reproxy.assets: '/:/assets/static1' # <------------!!! 
```

My goal here is to serve all routes to static folder EXCEPT `/whoami/(.*)` route

but turns out  that if I define `reproxy.assets` = `/` - it takes higher priority then what i defined in `reproxy.route`
