### ISSUE TITLE
Multiple domains support

### ISSUE THREAD

**Issue by skar404** [umputun/reproxy#69]
Multiple domains support,

Set domains on the app docker label 

Example:
```yml
  main:
    image: "main"
    labels:
      reproxy.host=main.host.com
         
  app:
    image: "app"
    labels:
      reproxy.host=app.host.com
   ```
