### ISSUE TITLE
Performance with file uploads

### ISSUE THREAD

**Issue by vitalik** [umputun/reproxy#71]
a simple 12Mb file takes 1.6 sec  to upload with reproxy

With reproxy:

```
time curl -X POST "http://localhost/api/upload" -H  "accept: application/json" -H  "Content-Type: multipart/form-data" -F "file=@12MB.txt"

0.01s user 0.01s system 1% cpu 1.614 total
```

-----

without :
```
time curl -X POST "http://localhost:8000/api/upload" -H  "accept: application/json" -H  "Content-Type: multipart/form-data" -F "file=@12MB.txt"

0.00s user 0.01s system 29% cpu 0.062 total
```
----

conf:
```
  reproxy:
    image: umputun/reproxy:master
    container_name: reproxy
    hostname: reproxy
    ports:
      - "80:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./files/static:/static
    environment:
      - LISTEN=0.0.0.0:8080
      - DOCKER_ENABLED=true
      - DEBUG=true
      - MAX_SIZE=20000000
````

**Comment by umputun** [comment]
I'm not sure how reproxy can add such a significant delay, there is no path here involving anything that heavy. Have you tried to repeat the test to see if the results consistent? Another good idea is to run reproxy without docker to eliminate this part because on some os running docker in the internal VM, any file access to a volume can be slow

**Comment by vitalik** [comment]
volumes seems not the case, here is my setup without any volume:


```YAML
services:
    reproxy:
      image: umputun/reproxy:master
      container_name: reproxy
      hostname: reproxy
      ports:
        - 80:8080
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
      environment:
        - LISTEN=0.0.0.0:8080
        - DOCKER_ENABLED=true
        - DEBUG=true
        - LOGGER_STDOUT=true
        - MAX_SIZE=20000000
  
    whoami:
      image: 'containous/whoami'
      container_name: whoami
      labels:
        reproxy.server: 'localhost'
```

test:

```
time curl -X POST -D - "http://localhost/whoami/" -H  "accept: application/json" -H  "Content-Type: multipart/form-data" -F "file=@12MB.txt"
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Date: Thu, 13 May 2021 06:51:09 GMT
Transfer-Encoding: chunked

Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.


0.01s user 0.03s system 2% cpu 1.566 total
```

note it gave 2 http responses actually:

```
HTTP/1.1 100 Continue
<pause>
HTTP/1.1 200 OK
```
