### ISSUE TITLE
Support multiple route pairs in docker labels

### ISSUE THREAD

**Issue by umputun** [umputun/reproxy#78]
re: https://github.com/umputun/reproxy/discussions/76

In some cases, one container may expose multiple endpoints, for example, public API and some admin API. They can be on different ports and the goal is to allow such functionality to be defined with docker provider (labels?)

I can think of two ways to implement it:

- add numeric suffix to reproxy.*.N, i.e. reproxy.server.1=example.com, reproxy.dest.1=blah and so on. This may increase the number of labels and could be ugly in extreme cases
- similar to the first approach but combine the rule in this style of static provider, i.e. `reproxy.1=m.example.com,/api/(.*)./someplace/$1,/ping`. This is harder to read but will minimize the number of labels

both approaches can be combined too, and the user can choose which one he likes better. The current labels should be supported too as we don't want to break compatibility for no good reason

if anyone has better ideas pls share

**Comment by umputun** [comment]
cc @avowkind

**Comment by avowkind** [comment]
Thanks for looking at this. 
Here's an example that might illustrate. 
- split the labels into multiple groups. 
- indicate which port each group should use. or assume from the order of the port defs 

```
version: '3.5'
services:
  computer-vision:
    image: pfr-computer-vision:latest
    ports:
      - 14000:14000 <-- port 1
      - 14001:14001  <-- port 2
    labels:
      reproxy.1.ping: '/api/v1/ping'
      reproxy.1.route: "(/api/v1)"
      reproxy.1.dest: "$scheme://$host:$port.1/$path"
      reproxy.1.enabled: true
      reproxy.2.ping: '/api/v2/ping'
      reproxy.2.route: "(/api/v2)"
      reproxy.2.port: 14001
      reproxy.2.dest: $$1
      reproxy.2.enabled: true 

```
